import type { Metadata } from "next";
import { Belanosima } from "next/font/google";
import "./globals.css";
import { lato } from "./fonts";

const belanosima = Belanosima({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-belanosima",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${belanosima.variable} ${lato.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
